env:
    global:
        - CC_TEST_REPORTER_ID=38d56875bbdffb56d914e7069334f0513024a29c54419ab3397ab79b15b9de30

language: python
python:
    # we want to test our package on several versions of Python 
    - 3.6
    - 3.7
    - 3.8

before_install:
    #make depends on poetry
    - pip install --upgrade pip
    - pip install poetry

install:
    - make install

script:
    # running flake8 linter and pytest tests
    - make check

# Pipe the coverage data to Code Climate
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
